### ISSUE TITLE
Listen for /support_foot and not just /walk_support_state

### ISSUE THREAD

**Issue by lilioid** [bit-bots/humanoid_base_footprint#1]
This should be done to increase compatibility with different action the robot can do.
For example a kick also needs to publish a support foot but it would not be logical to publish on /walk_support_state. It is also not practical to add a new subscriber to humanoid_base_footprint for every other action.

**Comment by SammyRamone** [comment]
ping @jgueldenstein is this still an open issue?

**Comment by SammyRamone** [comment]
currently the base_footprint listens to walk and kick and works. I will close this issue for now, since I don't expect any further support sttes in the near futur
