### ISSUE TITLE
Release rot-conv as a third party library into ROS2

### ISSUE THREAD

**Issue by ijnek** [bit-bots/humanoid_base_footprint#23]
The rot-conv library must be released into ROS2 for this package to be released into ROS2.
Alternatively, ``rot_conv::QuatNoEYaw`` is the only function being used from `rot_conv`, so perhaps we could simply reimplement that function?

**Comment by Flova** [comment]
I think rot_conv is quite useful as a library, (I think it is also used by other parts of our software), I, therefore, think it would be a nice addition to ros2.

**Comment by ijnek** [comment]
Sounds like it contains functionality that is well-tested and there are no alternative ROS libraries out there already with the functionality.

Guessing that the original repository https://github.com/AIS-Bonn/rot_conv_lib is currently unmaintained, could we transfer the [bitbots fork of rot_conv_lib](https://github.com/bit-bots/rot_conv_lib) across to ros-sports and release that?

@Flova I assume that's what you were thinking. If you're fine with that, feel free to do the transfer.

**Comment by SammyRamone** [comment]
I would also vote for releasing this package, as it is a generally usable library. I don't know much about copyrights and if we can do this like this. The original author also works for our university now (in a different research group). We could also ask him, what he prefers. What do you think @ijnek

**Comment by ijnek** [comment]
There shouldn't be an issue with us releasing the library since the original library is a BSD license. What would be good though, is if you can get in touch with the original author, to check whether the library is currently being maintained (the author is willing to accept bug fixes / feature additions).

**Is the original author willing to maintain the original library?**
* Yes: We follow [ReleaseThirdParty](http://wiki.ros.org/bloom/Tutorials/ReleaseThirdParty), and apply patches in the release repo to add a `package.xml`.
* No: We create a fork and release it.

**Comment by ijnek** [comment]
@SammyRamone Did you manage to get in touch with the author?

**Comment by pallgeuer** [comment]
Hey, I am the author of `rot_conv_lib`. Yes, I'm still maintaining it, but it was a very complete and tested release back in the day and no issues have been raised on the repository, so no actions were necessary so far. I would be happy to keep maintaining the library. That way you can use the ReleaseThirdParty pipeline for the release repo.

**Comment by ijnek** [comment]
Hi @pallgeuer, thanks for your work with the library and getting in touch with us about the maintenance status. I'll proceed with releasing it as a third party pipeline.

**Comment by ijnek** [comment]
Reuqesting for a new third-party release repository in https://github.com/ros2-gbp/ros2-gbp-github-org/issues/26

**Comment by ijnek** [comment]
The request has been accepted, will try and release it when I can get around to it.

**Comment by ijnek** [comment]
rot_conv has been released into the ROS ecosystem. The package name is ``rot_conv``.
