### ISSUE TITLE
Should either drop support for ROS2 Foxy and Galactic, or come up with alternatives to these problems

### ISSUE THREAD

**Issue by ijnek** [bit-bots/humanoid_base_footprint#27]
The master branch doesn't compile on ROS2 Foxy and Galactic, because of issues stated below:

* Some imports have been renamed from .h files to .hpp files recently in Rolling (and these changes have not been backported to Galactic).
    ```diff
    - #include <tf2_eigen/tf2_eigen.h>
    - #include <tf2_geometry_msgs/tf2_geometry_msgs.h>
    + #include <tf2_eigen/tf2_eigen.hpp>
    + #include <tf2_geometry_msgs/tf2_geometry_msgs.hpp>
    ```

* `rclcpp::Clock::sleep_until` is being used in `base_footprint.cpp`, but is a new feature in ROS2 Rolling, and didn't exist in ROS2 Foxy and Galactic

Two alternatives:

* Try and support Foxy and Galactic, on a "galactic" branch. Any future PRs will be backported if possible until something is absolutely un-backportable.
* Ditch Foxy and Galactic support because we haven't even made a release yet, and care about all the backporting business after we make our first release. This will involve removing CI for Focy and Galactic.

My instinct is option 2. Thoughts? @ros-sports/humanoid_base_footprint

**Comment by SammyRamone** [comment]
I would vote for option 2 (dropping support for foxy and galactic). I think it is too much effort. We also had other issues where things did not get pack-ported to galactic, that is why we use Rolling. I don't think anybody is really planning on staying on Galactic or Foxy for long.

**Comment by ijnek** [comment]
Although I don't mind dropping support for ROS2 Foxy and Galactic, from ROS2 Humble onwards, we would want to consider branching off supported distros when incompatible changes arise.

**Something that has to be kept in mind, is that Rolling will receive frequent and possibly compatibility-breaking releases. This could be extremely dangerous if a breaking update is released right before a competition.**

I do understand the problem your team faces too though. You make a bug fix or feature addition in one of the core ros2 libraries, for example, and you'd want to have those new changes immediately, but if you're using the latest stable distro you don't have access to those new changes. I don't have a good answer for how to deal with this.

**Comment by SammyRamone** [comment]
Yes that is a good idea.

You are right, this can be an issue when there are changes right before a competition. Still, I think it is the best way for us to use rolling at the moment.

**Comment by ijnek** [comment]
Reopenning, as #28 needs to be merged for this issue to be solved.
