### ISSUE TITLE
Publishing transforms by using tf2_ros::MessageFilter on JointStates

### ISSUE THREAD

**Issue by ijnek** [bit-bots/humanoid_base_footprint#32]
How about rather than having humanoid_base_footprint publish at a set frequency, we respond to transform changes using something like a [tf2::MesssageFilter](https://wiki.ros.org/tf2/Tutorials/Using%20stamped%20datatypes%20with%20tf2%3A%3AMessageFilter), as discussed in [[tf2] get new transform as soon as possible (callback)?](https://answers.ros.org/question/363803/tf2-get-new-transform-as-soon-as-possible-callback/). That way humanoid_base_footprint transforms become available whenever new data is available to calculate it.

As the tf we have to publish is `base_link -> base_footprint`, applying the filter to the JointStates topic seems appropriate.  Here is an [example for one done for the Nao robot in ROS1](https://github.com/ros-naoqi/nao_robot/blob/master/nao_description/src/base_footprint.cpp)

**Comment by SammyRamone** [comment]
Yes, I think it would be a good idea to restructure it this way.

**Comment by ijnek** [comment]
I will try and get this done today.

**Comment by ijnek** [comment]
This is taking quite a bit of time. If I can't get it working today, I'll raise a separate PR to fix https://github.com/ros-sports/humanoid_base_footprint/issues/30

**Comment by ijnek** [comment]
Turns out the reason for taking a long time on this was due to a bug in tf2_ros::MessageFilter, which I've proposed a [fix on ros2/geometry2](https://github.com/ros2/geometry2/pull/511). I will continue to work on this.

**Comment by Flova** [comment]
I sometimes ask myself if we are the only ones using ROS2 at the moment if such things happen in such core components...
This is obviously not the case, but I am a bit surprised nevertheless.

Edit: I thought it was for all message filters and not the tf2 ones, so they are less commonly used.

**Comment by ijnek** [comment]
So, after trying this for a while, I think there may be an issue with this approach.

Ideally humanoid_base_footprint should publish a tf from `base_link->base_footprint`, whenever one of the following events occur:
* the support foot changes
* one of the following tf changes:
  * `base_link->odom`
  * `base_link->r_sole`
  * `base_link->l_sole`

The tf `base_link->odom` usually comes from the odometry system, which can be calculated from JointState, IMU, visual odometry, or anything of choice. This means that synchronization with `joint_states(sensor_msgs::msg::JointState)` doesn't make sense if odometry is calculated from another source with it's own timestamps. (eg. IMU timestamps won't synchronize with JointState timestamps).

With this in mind, using the current method of publishing at a certain rate seems like a better method. I'm going to close this off, but feel free to continue the discussion or open another issue with an alternative method.
